fdroidserver: fix resource livecheck
`brew livecheck --resources fdroidserver` crashes with this error:
```
Error: fdroidserver: `url :stable` does not reference a checkable URL
```
There's no need to use `url :stable` method inside resource livecheck

Signed-off-by: botantony <antonsm21@gmail.com>